docling-project/docling-serve

.github/workflow/images.yml
Containerfile
Makefile
poetry.lock
pyproject.toml

This commit:
- Creates container file to build the image for cpu only and default "with gpu" images
- Adds workflow jobs to publish the images to ghcr.io and quay.io
- Makefile to build these images locally for linux/amd64 platform.

Publish docling-serve images to ghcr and quay container repositories

---

.github/workflows/images.yml
.gitignore
Makefile

Group GPU image generate for GHCR and QUAY in one job, and similarly group CPU only image generation for GHCR and QUAY in another job. These two jobs can now run concurrently.
By grouping the jobs for the same image type, it can use the docker layer cache to run the second job faster. If we separately build these images in four diffent and concurrent jobs, they won't be able to use the cache.
If this still takes significantly long, we probably have to generate image in it's own job, so that they can run concurrently, without leveraging cache of docker layers.
Also added make file target to lint the github workflows.

Enable concurrent running of the image generation jobs

---

.github/workflows/checks.yml
.github/workflows/images.yml

Github Action runners are running out of the space while building both the images in parallel.
This change will build the image sequentially and also clean up the cpu images before start building gpu image.

Run workflow jobs sequentially to avoid disk space outage

---

docling_serve/__main__.py

When reload is set, or when uvicorn workers are more than one, the application cannot start.
That's because Uvicorn requires the application to be passed as an import string (e.g., 'docling_serve.app:app'). This is because Uvicorn needs to manage multiple processes or watch for file changes, which requires knowing how to import the application.

Fix __main__ when workers > 1 or reload enabled

---

.github/workflows/images.yml

Fix missing `secrets: inherit` in the image publish pipeline

ci: fix missing secrets inherit

---

Makefile
README.md
start_server.sh

`start_server.sh` and docs were not updated after switching to uv.
I also added a paragraph on extra explaining how uv extras work.
`CONTRIBUTING.md` still mentions poetry. I haven't touched it because I'm not sure what the workflow is and what parts should be kept

chore: use uv in start_server.sh and update docs

---

Containerfile
README.md
docling_serve/__main__.py
docling_serve/docling_conversion.py
docling_serve/settings.py

By default images will contain the model weights and they will use them, i.e. the ENV `DOCLING_SERVE_ARTIFACTS_PATH` is set to the default location.
For letting the system still download the model weights, set the argument to an empty string, e.g.
```
docker run -p 5001:5001 -e DOCLING_SERVE_ARTIFACTS_PATH="" ghcr.io/ds4sd/docling-serve-cpu:main
```

fix: set DOCLING_SERVE_ARTIFACTS_PATH in images

---

docling_serve/docling_conversion.py

`hexdigest` is a little bit slower and there is no reason to use strings here.
even if you needed to be able to copypaste these keys for some reason you still can: `{b'\xf6\x9bg\xef\xd8\xa8\x8be\x92&\xbc\xaeq\x10\xaf^L\xbd\xd4\xaf': <docling.document_converter.DocumentConverter object at 0x7598596dacc0>}`

refactor: Use bytes as options key

---

.github/workflows/ci-images-dryrun.yml
.github/workflows/images.yml
.github/workflows/job-image.yml
Makefile

Avoiding confusion in the naming of the container images and simplifying the CI scripts.
Resolves #52

feat: New container images

---

.markdownlint-cli2.yaml
README.md

Remove comma in convert/source curl example to make it work.
Otherwise it fails with error message:
{"detail":[{"type":"json_invalid","loc":["body",607],"msg":"JSON decode error","input":{},"ctx":{"error":"Expecting property name enclosed in double quotes"}}]}%

fix(docs): Remove comma in convert/source curl example

---

docling_serve/__main__.py
docling_serve/app.py
uv.lock

I don't see version anywhere else in UI currently. I did what `--version` code does

feat: display version in fastapi docs

---

.markdownlint-cli2.yaml
.pre-commit-config.yaml
Containerfile
docling_serve/__main__.py
docling_serve/app.py
docling_serve/datamodel/convert.py
docling_serve/datamodel/engines.py
docling_serve/datamodel/requests.py
docling_serve/datamodel/responses.py
docling_serve/docling_conversion.py
docling_serve/engines/__init__.py
docling_serve/engines/async_local/orchestrator.py
docling_serve/engines/async_local/worker.py
docling_serve/engines/base_orchestrator.py
docling_serve/gradio_ui.py
docling_serve/response_preparation.py
docling_serve/settings.py
pyproject.toml
tests/test_1-file-all-outputs.py
tests/test_1-url-all-outputs.py
tests/test_1-url-async-ws.py
tests/test_1-url-async.py
tests/test_2-files-all-outputs.py
tests/test_2-urls-all-outputs.py
uv.lock

Introduce the Async compute API
```
/v1alpha/convert/source
/v1alpha/convert/file
/v1alpha/convert/source/async
/v1alpha/convert/file/async
/v1alpha/status/poll/{task_id}?wait=10
/v1alpha/status/ws/{task_id}
/v1alpha/result/{task_id}
```
Still TODO
Resolves #51

feat: Async api

---

Containerfile

Removed uv from container file since its not used at runtime.
Merging ARG and ENV also reduces number of layers from 23 to ~~15~~ 14.
Resolves #56 
Partially addresses #25 
I could not test this unfortunantely. Looks like something is breaking podman (even before my changes):
```
$ podman build . --build-arg='UV_SYNC_EXTRA_ARGS=--no-extra=cu124 --no-extra=rapidocr --no-extra=tesserocr' -t docling_serve
...
STEP 19/23: RUN echo "Downloading models..." &&     docling-tools models download -o "${DOCLING_SERVE_ARTIFACTS_PATH}" ${MODELS_LIST} &&     chown -R 1001:0 /opt/app-root/src/.cache &&     chmod -R g=u /opt/app-ro
ot/src/.cache
Downloading models...
There was a problem when trying to write in your cache folder …
```

fix: Remove uv from image, merge ARG and ENV declarations

---

Containerfile

Increase the download timeout to avoid CI failure because of bad networking connectivity to HF.

chore: extend timeout for downloading the model artifacts

---

docling_serve/app.py
docling_serve/docling_conversion.py
docling_serve/settings.py

Switching from an infinite cache to LRU controlled by the parameter `DOCLING_SERVE_OPTIONS_CACHE_SIZE` (default 2).
Resolves #86

fix: avoid exploding options cache using lru and expose size parameter

---

docling_serve/app.py
docling_serve/settings.py

Expose CORS parameters as ENV variables, e.g.
```
DOCLING_SERVE_CORS_ORIGINS='["localhost"]' docling-serve run
```
Because of what was found in #99, it is better to expose the parameter only as ENV.
Resolves #88

fix: allow changes in CORS settings

---

.markdownlint-cli2.yaml
Makefile
README.md
docs/README.md
docs/configuration.md
docs/deployment.md
docs/development.md
docs/usage.md

docs: simplify README and move details to docs

---

Containerfile

According to https://docs.docker.com/reference/dockerfile/#impact-on-build-caching `ARG` casuse cache invalidation.
Overwriting uv args or model list doesn't reinstall OS packages anymore

fix: Move ARGs to prevent cache invalidation

---

docling_serve/app.py
docling_serve/gradio_ui.py
docling_serve/settings.py
docs/configuration.md

The new option `DOCLING_SERVE_STATIC_PATH` allows to run the Swagger UI and the Gradio UI completely offline.
Example on how to get the static files:
```sh
mkdir -p ~/.cache/docling/static
cd ~/.cache/docling/static
curl -LO https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui-bundle.js
curl -LO https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui.css
curl -LO https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js
curl -o docling-components.js https://unpkg.com/@docling/docling-components@0.0.3/dist/index.js
```

feat: Offline static files

---

docling_serve/__main__.py
docling_serve/settings.py
docs/configuration.md
docs/deploy-examples/docling-serve-oauth.yaml
docs/deployment.md

1. Expose TLS options of Uvicorn
2. Use the automatic in-cluster certificate for the communication between containers
3. Use OAuth-Proxy for authenticatio
Resolves #111

feat: Expose TLS settings and example deploy with oauth-proxy

---

docling_serve/gradio_ui.py

feat(UI): change UI to use async endpoints

---

docling_serve/datamodel/convert.py
docling_serve/docling_conversion.py
docling_serve/gradio_ui.py
docling_serve/settings.py
pyproject.toml
tests/test_1-file-all-outputs.py
tests/test_1-url-all-outputs.py
uv.lock

- Pydantic 2.11 is currently incompatible with Gradio, so when using the UI we have to pin it
- ~Expose the choice for the vlm pipeline. Refs #103~ (it will be in its own PR)
Resolves #130
Resolves #134

feat: Expose more conversion options

---

docling_serve/response_preparation.py
tests/test_fastapi_endpoints.py

This PR adds `fastapi` test to run with `pytest` cli
changed deprecated `export_to_document_tokens` to new `export_to_doctags`

test: add tests with fastapi client

---

docs/usage.md

Fixing a small typo in usage.md on the parameters

docs: fixing small typo in docs

---

docling_serve/datamodel/convert.py
docling_serve/docling_conversion.py
docs/usage.md

From version [v2.30.0](https://github.com/docling-project/docling/releases/tag/v2.30.0) Docling uses a 5% threshold for selecting which images to process. This PR allows users to configure the parameter and use `picture_description_area_threshold=0` to restore the previous behavior.

fix: allow users to set the area threshold for picture descriptions

---

docling_serve/gradio_ui.py

Resolves #179 
**Closed points**
- This version of docling-components switches to a different build and the package distribution files have changed. This could break docling-serve using static assets where the above files would be downloaded up front. Where are these files being copied over?

feat: Figure annotations @ docling components 0.0.7

---

docling_serve/app.py
docling_serve/datamodel/responses.py

Allow users to manually clear the models cache.
⚠️ there is no guarantee that the offloading is not mixed with the current tasks which are in process.
Resolves #70

feat: api to trigger offloading the models

---

README.md
docs/deploy-examples/docling-model-cache-deployment.yaml
docs/deploy-examples/docling-model-cache-job.yaml
docs/deploy-examples/docling-model-cache-pvc.yaml
docs/pre-loading-models.md

Changes to documentation:
- instructions on how to download model weights into persistent volume
- example yaml manifests
Resolves #191

docs: Example and instructions on how to load model weights to persistent volume

---

.gitignore
docs/deploy-examples/docling-serve-replicas-w-sticky-sessions.yaml
docs/deployment.md

- adds openshift replicasets with sticky sessions examples

docs: add openshift replicasets examples

---

docling_serve/gradio_ui.py

This is a step for supporting WEBP format.
I think https://github.com/docling-project/docling/pull/1415 missed adding `webp` to `FormatToMimeType`.
I will send a PR for docling repo and link it here.

feat: Read supported file extensions from docling

---

docs/usage.md

Changes the `params` example to the full `picture_description_api` example.

docs: change the doc example

---

os-packages.txt

On RHEL and Fedora the tesseract installation needs an additional package:
dnf install tesseract tesseract-devel tesseract-langpack-eng **tesseract-osd** leptonica-devel 
**tesseract-osd** was missing.
Resolves https://github.com/docling-project/docling/issues/1751

fix: missing tesseract osd

---

docs/deployment.md

Update curl command to use the V1 API. As it is now, it fails since it's still using v1alpha.

docs: Update deployment examples to use v1 API

---

docling_serve/app.py

fix: add missing response type in sync endpoints

---

docs/deploy-examples/docling-serve-rq-workers.yaml
docs/deployment.md

Intentionally didn't set tag to ":main" so users don't pull non-release version.

docs: example of docling-serve deployment in the RQ engine mode

---

.github/scripts/release.sh
.github/workflows/actionlint.yml
.github/workflows/cd.yml
.github/workflows/job-build.yml
.github/workflows/job-checks.yml
.github/workflows/job-image.yml

regarding build and tests:
- updated actions versions
- the new test stage, runs after the build, and so it uses the build cache, one is just exporting the build cache to docker 
```load: true # == '--output=type=docker'```
- it runs for all images
- stage does: mounts container, checks health, runs pytest, cleanup
- adds images tests for released, `-cpu` and `-cu*`  (commented out now,maybe not needed anymore)
regarding releases:
- adds docling packages versions to changelog, from ```uv.lock```
ref https://github.com/docling-project/docling-serve/issues/302

ci: workflow improvements
