.github/actions/setup-poetry/action.yml
.github/workflows/actionlint.yml
.github/workflows/checks.yml
.gitignore
.markdownlint-cli2.yaml
CODE_OF_CONDUCT.md
CONTRIBUTING.md
Makefile
README.md

to ensure the code maintenance. Thanks to docling
project- took some good bits around python linting from the project.
These checks are also added in the markdown, so that user can run these checks locally to recreate the
errors.

Add python, markdown and github action linter

---

.github/workflows/images.yml

Build and push the images on tags/releases.

ci: build on tags

---

.github/workflows/images.yml
Containerfile

- Use port 5001
- Publish cpu only arm64 image to quay.io as well

Minor fixes -

---

start_server.sh

fix: UVICORN_WORKERS propagation in start_server

---

README.md

Readme additions for a quickstart running of docling-serve.

docs:Readme additions for running

---

docling_serve/app.py
docling_serve/datamodel/convert.py
docling_serve/datamodel/requests.py
docling_serve/datamodel/responses.py
docling_serve/docling_conversion.py
docling_serve/engines/async_local/orchestrator.py
docling_serve/engines/async_local/worker.py
docling_serve/helper_functions.py
docling_serve/response_preparation.py
pyproject.toml

@Fogapod this is redoing your PR #59 on the latest main and adding the ruff rules in the pre-commit.

chore: Remove deprecated type aliases and run as pre-commit

---

.github/scripts/release.sh

chore: update uv.lock with new release version

---

docling_serve/datamodel/convert.py
docling_serve/docling_conversion.py
docling_serve/gradio_ui.py

feat: expose options for new features

---

docling_serve/gradio_ui.py

fix(ui): use --port parameter and avoid failing when image is not found

---

docling_serve/__main__.py

Unfortunately, when `uvicorn` spawns a subprocess, the singleton settings are not propagated. This happens only when the parameters are specified as CLI options.
For the moment, we better warn the users that in those cases the preferred approach is using ENV variables for the parameters.
Resolves #84
Refs #88

fix: add warning when using incompatible parameters

---

docling_serve/__main__.py
docling_serve/settings.py

fix: increase timeout_keep_alive and allow parameter changes

---

docling_serve/datamodel/convert.py
docling_serve/datamodel/engines.py
docling_serve/datamodel/task.py
docling_serve/docling_conversion.py
docling_serve/engines/async_local/orchestrator.py
docling_serve/engines/base_orchestrator.py
docling_serve/settings.py
pyproject.toml
uv.lock

Update to the new Docling release and use the factory mechanism in the options selection.

feat: Update to Docling 2.28

---

docs/deploy-examples/docling-serve-oauth.yaml

docs: fix image tag

---

docling_serve/gradio_ui.py

Resolves https://github.com/docling-project/docling/issues/1386

fix: picture caption visuals

---

.markdownlint-cli2.yaml
docs/deploy-examples/compose-gpu.yaml
docs/deploy-examples/docling-serve-simple.yaml
docs/deployment.md

adds deployment examples to leverage the nvidia cuda image
- compose for local deployment
- openshift deployment with service

docs: update deployment examples

---

docs/deploy-examples/docling-serve-oauth.yaml

docs: fix required permissions for oauth2-proxy requests

---

docling_serve/datamodel/convert.py
docling_serve/docling_conversion.py
docling_serve/gradio_ui.py
pyproject.toml
uv.lock

feat: Add option for vlm pipeline

---

docling_serve/datamodel/convert.py
docs/configuration.md
docs/usage.md

Add more entries in the configuration and usage docs.

docs: vlm and picture description options

---

docling_serve/docling_conversion.py

fix: produce image artifacts in referenced mode

---

docling_serve/app.py
docling_serve/settings.py
docs/configuration.md

fix: expose max wait time in sync endpoints

---

docs/usage.md

- Add docs for async endpoints
- Fix usage for file upload. Refs #187

docs: async api usage and fixes

---

README.md
docs/configuration.md
docs/deploy-examples/docling-model-cache-deployment.yaml
docs/deploy-examples/docling-serve-oauth.yaml
docs/deploy-examples/docling-serve-replicas-w-sticky-sessions.yaml
docs/deploy-examples/docling-serve-simple.yaml
pyproject.toml

docs: Update example resources and improve README

---

docs/configuration.md

docs: Update typo

---

docling_serve/app.py

This PR adds endpoint that returns downgraded version of `openapi` version 3.1 to 3.0.x
Resolves #283.

feat: add 3.0 openapi endpoint

---

docling_serve/app.py
docling_serve/auth.py
docling_serve/gradio_ui.py
docling_serve/settings.py
docs/configuration.md
docs/usage.md
tests/test_1-file-all-outputs.py
tests/test_1-file-async.py
tests/test_1-url-all-outputs.py
tests/test_1-url-async-ws.py
tests/test_1-url-async.py
tests/test_2-files-all-outputs.py
tests/test_2-urls-all-outputs.py
tests/test_2-urls-async-all-outputs.py
tests/test_fastapi_endpoints.py
tests/test_file_opts.py
tests/test_results_clear.py

feat: Add configuration option for apikey security

---

docs/usage.md

docs: fix docs for websocket breaking condition
